name: Build from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: v14.x.x
    - name: Install Dependencies
      run: yarn
    - name: Run tests
      run: yarn build
    - name: Build to kroneman.github.io
      env:
        PAGES_DEPLOYMENT_EMAIL: ${{ secrets.PAGES_DEPLOYMENT_EMAIL }}
        PAGES_DEPLOYMENT_NAME: ${{ secrets.PAGES_DEPLOYMENT_NAME }}
        PAGES_DEPLOYMENT_TOKEN: ${{ secrets.PAGES_DEPLOYMENT_TOKEN }}
        PAGES_DEPLOYMENT_USER: ${{ secrets.PAGES_DEPLOYMENT_USER }}
      run: ${GITHUB_WORKSPACE}/bin/deploy-v2
